#!/bin/bash

set -e

echo "🚀 Podly Lambda Build & Deploy Script"
echo "======================================"

# カレントディレクトリの確認
if [ ! -f "main.tf" ]; then
    echo "❌ main.tf not found. Please run this script from podly-tr directory."
    exit 1
fi

# Lambda関数のビルド
echo "📦 Building Lambda functions..."
cd ../podly-lambda

# 依存関係のインストール
npm install

# ビルド実行
npm run build

echo "✅ Lambda functions built successfully"

# Terraformディレクトリに戻る
cd ../podly-tr

# terraform.tfvarsの存在確認
if [ ! -f "terraform.tfvars" ]; then
    echo "❌ terraform.tfvars not found. Please create it from terraform.tfvars.example"
    exit 1
fi

# Lambda関数のハッシュを計算して更新
echo "🔍 Calculating Lambda function hashes..."

# create-script.zipのハッシュを計算
if [ -f "../podly-lambda/dist/create-script.zip" ]; then
    if command -v sha256sum &> /dev/null; then
        CREATE_SCRIPT_HASH=$(sha256sum "../podly-lambda/dist/create-script.zip" | cut -d' ' -f1)
    else
        CREATE_SCRIPT_HASH=$(shasum -a 256 "../podly-lambda/dist/create-script.zip" | cut -d' ' -f1)
    fi
    echo "📦 create-script.zip hash: $CREATE_SCRIPT_HASH"
else
    echo "❌ create-script.zip not found"
    exit 1
fi

# create-preview-audio.zipのハッシュを計算
if [ -f "../podly-lambda/dist/create-preview-audio.zip" ]; then
    if command -v sha256sum &> /dev/null; then
        CREATE_PREVIEW_AUDIO_HASH=$(sha256sum "../podly-lambda/dist/create-preview-audio.zip" | cut -d' ' -f1)
    else
        CREATE_PREVIEW_AUDIO_HASH=$(shasum -a 256 "../podly-lambda/dist/create-preview-audio.zip" | cut -d' ' -f1)
    fi
    echo "📦 create-preview-audio.zip hash: $CREATE_PREVIEW_AUDIO_HASH"
else
    echo "❌ create-preview-audio.zip not found"
    exit 1
fi

# terraform.tfvarsファイルを更新
echo "📝 Updating terraform.tfvars with new hashes..."
cp terraform.tfvars terraform.tfvars.backup
# 新しいterraform.tfvarsファイルを作成
cat > terraform.tfvars << EOF
# AWS Configuration
aws_region = "ap-northeast-1"

# Project Configuration
project_name = "podly"
environment  = "dev"


# Lambda Packages (auto-generated by build script)
lambda_packages = {
  create_script = {
    filename         = "../podly-lambda/dist/create-script.zip"
    source_code_hash = "$CREATE_SCRIPT_HASH"
  }
  create_preview_audio = {
    filename         = "../podly-lambda/dist/create-preview-audio.zip"
    source_code_hash = "$CREATE_PREVIEW_AUDIO_HASH"
  }
}

# CORS Configuration
cors_allow_origins = ["*"]
cors_allow_methods = ["GET", "POST", "OPTIONS"]
cors_allow_headers = ["Content-Type", "X-Amz-Date", "Authorization", "X-Api-Key", "X-Amz-Security-Token"]
EOF

echo "✅ terraform.tfvars updated successfully"


# FFmpeg Layerの確認
if [ ! -f "ffmpeg-layer.zip" ]; then
    echo "⚠️  ffmpeg-layer.zip not found. Downloading..."
    # 例: 公開されているLayerをダウンロード（実際のURLに置き換える）
    echo "Please manually download or create ffmpeg-layer.zip for your region"
    echo "You can use: https://github.com/serverlessrepo/serverlessrepo-ffmpeg-layer"
    exit 1
fi


